### ISSUE TITLE
Node not found 

### ISSUE THREAD

**Issue by hno2** [cqql/pelican-katex#8]
Hey, 

when creating files with latest pelican (4.6.0) I get the following error: 
 ```
[Errno 2] No such file or directory: 'node': 'node'
  |___
  | Traceback (most recent call last):
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican/generators.py", line 622, in generate_context
  |     context_sender=self)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican/readers.py", line 573, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican/readers.py", line 337, in read
  |     content = self._md.convert(text)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/markdown/core.py", line 267, in convert
  |     newRoot = treeprocessor.run(root)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/markdown/treeprocessors.py", line 370, in run
  |     self.__handleInline(text), child
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/markdown/treeprocessors.py", line 131, in __handleInline
  |     self.inlinePatterns[patternIndex], data, patternIndex, startIndex
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/markdown/treeprocessors.py", line 271, in __applyPattern
  |     node, start, end = pattern.handleMatch(match, data)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican_katex/markdown.py", line 71, in handleMatch
  |     rendered = render_latex(latex, {"displayMode": display_mode})
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican_katex/rendering.py", line 318, in render_latex
  |     server = RenderServer.get()
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican_katex/rendering.py", line 228, in get
  |     cls.RENDER_SERVER = RenderServer.start()
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican_katex/rendering.py", line 206, in start
  |     process, sock = cls.start_unix_socket(rundir, KATEX_STARTUP_TIMEOUT)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/site-packages/pelican_katex/rendering.py", line 141, in start_unix_socket
  |     process = Popen(cmd, stdin=PIPE, stdout=PIPE, cwd=rundir)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/subprocess.py", line 800, in __init__
  |     restore_signals, start_new_session)
  |   File "/Applications/Utilities/miniconda3/envs/pelican/lib/python3.7/subprocess.py", line 1551, in _execute_child
  |     raise child_exception_type(errno_num, err_msg, err_filename)
  | FileNotFoundError: [Errno 2] No such file or directory: 'node': 'node'
```
Thanks in Advance for your help!

**Comment by hno2** [comment]
Sorry, that was stupid, somehow nodejs vanished from my PATH Variable.
